destination:
  namespace: dev
global:
  source:
    targetRevision: master
    path: dev
app1:
  enabled: true
  image:
    tag: fe61325d9261dfc5ada4ae6800be381224031d88
  replicaCount: 4
app2:
  enabled: true
  image:
    tag: b5d52e6cbf186ad778ce0bc47979acfdb9f4d1df
  replicaCount: 2
